# Generated by Django 5.0.4 on 2024-11-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='schema',
            field=models.TextField(),
        ),
    ]
