# Generated by Django 5.0.4 on 2024-11-28 23:56

import dynamic_forms.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0002_alter_form_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='schema',
            field=dynamic_forms.models.FormField(),
        ),
    ]
