# Generated by Django 5.0.4 on 2024-12-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0004_formresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='FormResponseData',
        ),
    ]
